### PR TITLE
Decouple product setup.

### LINKED ISSUE #68: Proper way to setup stripe products and skus?
Noticing that the setup script is pretty inconsistent and would much rather have it as a one off script to run instead of something that runs every time you run the server. Current implementation seems really buggy. I just went to the site it setup the products, i refresh and now the page doesnt load and server says "already in progress...". It also seems like whenever i change the stripe product info everything breaks. I've had to wipe all my stripe test data 10 times now.

### PR DESCRIPTION
**Pull request by thorsten-stripe**
closes #68 

* Make server/node/setup.js standalone script.
* Remove product exist checking which relies on hardcoded product names.
* Run product setup script on `postinstall` hook.

### CODE REVIEW

**Comment by thorsten-stripe** [comment]
@adreyfus-stripe @mikeshaw-stripe any idea how we can create a similar experience for the other servers? Josh made a fair point[0] that the tight coupling to the product names makes it difficult for folks to untangle and change the product details.

I was thinking to maybe instead call the setup scripts for the other servers on `GET /setup` but maybe there are similar postinstall hooks for some of the other dependency installers? Wdyt?

[0] https://github.com/stripe/stripe-payments-demo/issues/68

**Comment by thorsten-stripe** [comment]
@youssef-stripe for the PHP server

**Comment by mikeshaw-stripe** [comment]
Hmmm for Ruby and Python I dont know of a way to do it using pip/bundler. But we can just move the product stuff to a setup.rb or setup.py file and just add a setup to run it in the Readme

**Comment by adreyfus-stripe** [comment]
Ultimately I think moving this to a more language agnostic setup script would be best

**Comment by thorsten-stripe** [comment]
I like that. For the time being maybe we can have everyone use the node setup script and add running `npm run setup-products` to the README files of the none-node backends. That means we can remove the setup scripts from all other backends, which is nice. Or do you think it's unreasonable to expect everyone to have node & npm installed?

**Comment by mikeshaw-stripe** [comment]
I think it's pretty unreasonable. Most OS's come with python. (Bar windows maybe). Maybe a language where a high percentage of possible users will already have the language installed

**Comment by thorsten-stripe** [comment]
Fair. I'm going to merge this now though as it is an improvement for the Node version. We should figure out a central approach in the future though.

**Comment by youssef-stripe** [comment]
Crazy idea: we could have an online setup page. Something like https://stripe-payments-demo.appspot.com/setup. It would use Standard connect to set up everything needed on a Stripe account to be used by this project.

**Pull request merged**
